### ISSUE TITLE
Errors with Ubuntu 20.04 and Postgresql 12.4

### ISSUE THREAD

**Issue by holyoaks** [eradman/ephemeralpg#3]
I have been using pg_tmp in a Docker container with Postgresql 10 on Ubuntu 18 for a while without problems. Today I created a new Docker container running Ubuntu 20.04 and Postgresql 12.4, and when I try to run `pg_tmp -t` I get:
`/usr/local/bin/pg_tmp: line 43: initdb: command not found`

When I try `psql $(pg_tmp)` I get the same error. How can I help figure out what's going on?

**Comment by eradman** [comment]
Which packages do you have installed? (`apt list --installed  | grep postgresql`)

**Comment by holyoaks** [comment]
Actually, I just figured it out. I had a script setting the path, and the script got missed when we bumped everything up to 12. The script still had 10 in the path. Changed that and everything is working properly again. You can close the issue. Thanks!

Shawn

**Comment by eradman** [comment]
Thanks @holyoaks! Closing
